0.2 add main-ut.cpp
anraf1001/testing pull request #6
Opened 2020-07-29 20:48 UTC by majkel84

new file added
CMakeList udpated

2020-07-29 21:18 UTC, Vicx95 submitted a review, later dismissed

2020-07-30 07:05 UTC, anraf1001 commented
Why do you want to add second main for tests? We've already added `gtest_main` in `CMakeLists.txt`
Line 63:
```cmake
target_link_libraries(${PROJECT_NAME}-ut PUBLIC ${PROJECT_NAME}-lib gtest_main)
```

2020-08-03 17:02 UTC, arafalski requested changes

2020-08-03 17:02 UTC, anraf1001 commented on bowling/main-ut.cpp
> +}
Redundant file

2020-08-03 18:35 UTC, majkel84 commented on bowling/main-ut.cpp
> +}
done

2020-08-03 19:08 UTC, arafalski approved these changes

2020-08-04 14:00 UTC, arafalski requested changes
Rebase/merge with anraf1001:homework
Solve conflicts

2020-08-05 15:14 UTC, merged